"""Centralized Russian UI texts."""

from __future__ import annotations

from typing import Any

TEXTS: dict[str, str] = {
    "tabs.sort": "Сортировка",
    "tabs.duplicates": "Дубликаты",
    "folders.title": "Папки",
    "folders.input": "Папка с файлами:",
    "folders.output": "Папка для результата:",
    "folders.pick": "Выбрать...",
    "folders.process": "Что обрабатывать:",
    "folders.speed": "Скорость обработки (потоков):",
    "folders.tag_mode.section": "Режим тегов",
    "folders.tag_mode.strict_radio": "Пресет: мои теги",
    "folders.tag_mode.auto_radio": "Автокатегории (умно)",
    "folders.tag_mode.free_radio": "Теги нейронки",
    "folders.tag_mode.show_list": "Показать список папок…",
    "folders.tag_mode.hint_strict": (
        "Ваш текущий преднастроенный набор папок без изменений (кнопка «Показать список»). "
        "Подходит для больших коллекций (десятки тысяч файлов): предсказуемая структура каталога."
    ),
    "folders.tag_mode.hint_free": (
        "Модель может придумывать новые имена папок (в т.ч. вида a/b/c). "
        "Для очень больших библиотек это может дать тысячи разных папок — удобнее сначала прогнать на подпапке или использовать фиксированный список."
    ),
    "folders.tag_mode.hint_auto": (
        "Гибридный режим: сначала ваш пресет, затем новые категории через стабилизатор. "
        "Синонимы вроде car/cars/vehicle/auto схлопываются, глубина папок ограничена, случайный мусор отсекается."
    ),
    "folders.tags.dialog_title": "Фиксированные папки (канонический список)",
    "sort.log_mode_strict": "Режим папок: пресет «мои теги» (текущий фиксированный список).",
    "sort.log_mode_auto": "Режим папок: оптимизированные автокатегории (пресет + стабилизированные новые папки).",
    "sort.log_mode_free": "Режим папок: свободные теги (модель может создавать новые папки).",
    "sort.review_first": "Review-first",
    "sort.warn_large_library_free": (
        "Подсказка: при 50k+ файлов свободный режим может раздувать число папок; "
        "кеш по хешу ускоряет повторный прогон, но первый проход всё равно вызывает API по каждому новому файлу."
    ),
    "sort.warn_many_files_free": (
        "Внимание: в папке найдено {n} файлов при свободном режиме тегов — возможны тысячи уникальных подпапок. "
        "Рассмотрите фиксированный список или разбивку по подпапкам."
    ),
    "buttons.close": "Закрыть",
    "buttons.apply": "Применить",
    "buttons.save": "Сохранить",
    "prompt.title": "Дополнительные инструкции",
    "prompt.extra": "Инструкции для модели (опционально):",
    "prompt.composer": "Композер промпта…",
    "prompt.composer.title": "Композер промпта",
    "prompt.composer.context": "Контекст для распознавания владельца / питомцев / личных правил:",
    "prompt.composer.extra": "Дополнительные инструкции для модели:",
    "prompt.aliases": "Алиасы категорий…",
    "prompt.aliases.title": "Алиасы автокатегорий",
    "prompt.aliases.hint": "JSON-словарь: что модель может написать -> во что это нормализовать. Пример: {\"auto\": \"vehicles\", \"bmw/car\": \"vehicles/bmw\"}",
    "prompt.aliases.saved": "Алиасы категорий сохранены.",
    "lm.title": "LM Studio / OpenAI-совместимый API",
    "lm.refresh_models": "Обновить список моделей",
    "lm.profile": "Профиль:",
    "lm.profile.save": "Сохранить профиль",
    "lm.profile.saved": "Профиль модели сохранён: {name}",
    "lm.profile.applied": "Профиль модели применён: {name} ({model}).",
    "lm.benchmark": "Бенчмарк",
    "lm.benchmark.start": "Бенчмарк vision-моделей: {n} кандидатов...",
    "lm.benchmark.no_models": "Бенчмарк: сначала обновите список моделей.",
    "lm.benchmark.empty": "Бенчмарк: нет результатов.",
    "lm.benchmark.error": "Бенчмарк: ошибка {err}",
    "lm.benchmark.best": "Бенчмарк: выбрана модель {model}, latency={latency} с, score={score}.",
    "lm.models.placeholder": "— нажмите «Обновить список моделей» —",
    "lm.vision.unknown": "Vision: не проверено",
    "lm.vision.ok": "Vision: OK ({hint})",
    "lm.vision.error": "Vision: ошибка ({hint})",
    "lm.vision.error_short": "Vision: ошибка",
    "lm.vision.selftest_ok": "Vision: самотест OK",
    "lm.vision.selftest_error": "Vision: самотест с ошибкой",
    "buttons.start": "Старт",
    "buttons.pause": "Пауза",
    "buttons.resume": "Продолжить",
    "buttons.stop": "Стоп",
    "buttons.clear_cache": "Очистить кеш",
    "eta.left": "Осталось: —",
    "eta.estimate_after_first": "Осталось: оценка после первого файла...",
    "eta.approx": "Осталось примерно: {eta}",
    "eta.counting": "Осталось: считаю...",
    "health.idle": "LM health: —",
    "health.api": "LM health: запросов {calls}, avg {avg} с, ошибок {errors}, review {review}",
    "log.title": "Лог:",
    "cache.warn_busy": "Недоступно",
    "cache.warn_stop_first": "Остановите сортировку перед очисткой кеша.",
    "cache.warn_probe_wait": "Дождитесь завершения проверки API.",
    "cache.ask.title": "Очистка кеша",
    "cache.ask.text": "Что очистить?\n\nДа — кеш сортировки\nНет — кеш дубликатов\nОтмена — оба кеша",
    "cache.log.cleared_sort": "Кеш сортировки очищен (записей: {count}).",
    "cache.log.cleared_dup": "Кеш дубликатов очищен (сигнатур: {count}).",
    "cache.log.cleared_both": "Оба кеша очищены (сортировка: {sort_count}, дубликаты: {dup_count}).",
    "cache.error": "Ошибка",
    "vision.meta.yes": "метаданные: vision",
    "vision.meta.no": "метаданные: вероятно текст",
    "vision.meta.none": "метаданные: нет данных",
    # --- Дубликаты: секции и общие ---
    "dup.section.source": "1. Источник и режим",
    "dup.section.accuracy": "2. Режим поиска, политика «оставить» и LLM",
    "dup.section.scan": "3. Управление сканированием",
    "dup.section.advanced": "Дополнительные настройки",
    "dup.section.results": "4. Результаты и фильтры",
    "dup.section.actions": "5. Действия с отмеченными файлами",
    "dup.folder.title": "Папка для поиска дубликатов",
    "dup.folder.placeholder": "Рекурсивный обход подпапок",
    "dup.folder.pick": "Выбрать…",
    "dup.pick_dir.title": "Папка для поиска дубликатов",
    "dup.media": "Медиа:",
    "dup.media.photos": "Только фото",
    "dup.media.photos_video": "Фото + видео",
    "dup.workers": "Потоки:",
    "dup.workers.hint": "Сколько файлов обрабатывать одновременно при сканировании (обычно достаточно 3).",
    "dup.preset": "Режим поиска:",
    "dup.accuracy.fast": "Только полные копии (быстро)",
    "dup.accuracy.balanced": "Обычный — копии и похожие снимки",
    "dup.accuracy.strict": "Тщательно — меньше ложных совпадений",
    "dup.accuracy.deep": "Максимум — глубже и дольше, для сложных папок",
    "dup.method.blurb_fast": "Ищет только файлы с одинаковым содержимым (полные копии). Самый быстрый режим; похожие, но не идентичные снимки не попадут в одну группу.",
    "dup.method.blurb_balanced": "Сначала полные копии, затем похожие фото и кадры из видео по внешнему виду. Без проверки нейросетью — быстрее, чем режимы с LLM.",
    "dup.method.blurb_strict": "Те же этапы, что в обычном режиме, но сравнение строже: меньше случайных совпадений, зато редкие «хитрые» дубли могут не попасть в группу.",
    "dup.method.blurb_deep": "Шире ищет похожие снимки. Подходит для больших и пёстрых коллекций; при желании включите проверку спорных пар через модель (флажок ниже).",
    "dup.method.llm_addon": "Включена дополнительная проверка спорных пар через выбранную модель — дольше по времени, нужны API и ffmpeg для кадров из видео.",
    "dup.llm.checkbox": "Проверять спорные пары через LLM при сканировании (дольше; нужны vision-модель и ffmpeg для кадров видео)",
    "dup.llm.block_title": "API и модель для LLM при скане",
    "dup.llm.video_hint": "Для видео берётся кадр через ffmpeg (или fallback); без этого точность ниже.",
    "dup.keep_policy": "Кого оставить в группе (подсказка по умолчанию):",
    "dup.keep.largest_px": "Самый большой (px)",
    "dup.keep.newest": "Самый новый",
    "dup.keep.largest_file": "Самый тяжёлый",
    "dup.scan": "Сканировать",
    "dup.regroup": "Перегруппировать из кеша",
    "dup.advanced.toggle_show": "Показать дополнительно",
    "dup.advanced.toggle_hide": "Скрыть дополнительно",
    "dup.force_recompute": "Пересчитать сигнатуры",
    "dup.bulk.skip_small": "Пропустить малые группы",
    "dup.bulk.unskip_all": "Снять пропуск со всех",
    "dup.bulk.suggested_keep": "Подставить «оставить» по подсказке",
    "dup.profile.save": "Сохранить профиль",
    "dup.profile.dialog_save": "Профили",
    "dup.profile.dialog_load": "Профили",
    "dup.profile.load": "Загрузить профиль",
    "dup.undo_log": "Журнал удалений",
    "dup.filter.type": "Тип групп:",
    "dup.filter.type.all": "Все",
    "dup.filter.type.exact": "Только байтовые дубли",
    "dup.filter.type.similar": "Только похожие",
    "dup.filter.skip": "Пропуск:",
    "dup.filter.skip.all": "Все",
    "dup.filter.skip.skipped": "Только пропущенные",
    "dup.filter.skip.active": "Только активные",
    "dup.filter.min_size": "Мин. файлов в группе:",
    "dup.filter.sort": "Сортировка:",
    "dup.sort.size_desc": "Сначала крупные группы",
    "dup.sort.size_asc": "Сначала мелкие",
    "dup.sort.name": "По имени файла",
    "dup.sort.type": "Тип (похожие / байтовые)",
    "dup.jump.label": "Перейти к группе:",
    "dup.jump.placeholder": "— выберите —",
    "dup.nav.label": "№ (по фильтрам):",
    "dup.nav.go": "Перейти",
    "dup.nav.prev": "◀ Назад",
    "dup.nav.next": "Вперёд ▶",
    "dup.nav.hint": "Позиция: {cur} / {total}",
    "dup.viewer.title": "Просмотр групп дубликатов",
    "dup.viewer.hint": "Крупные превью и отметки «оставить» / «утвердить» — в отдельном окне (кнопка ниже). Удаление и предпросмотр учитывают только группы с галочкой «Утвердить».",
    "dup.viewer.open": "Открыть окно просмотра групп",
    "dup.viewer.hotkeys": "В окне просмотра: Пробел — утвердить группу (не в поле «№», не на чекбоксе). Стрелки — предыдущая / следующая группа (работают и при фокусе на области превью).",
    "dup.viewer.empty": "Нет групп по текущим фильтрам.",
    "dup.approve.progress": "Утверждено групп: {approved} / {total}",
    "dup.review.progress": "Просмотрено групп: {done} / {total}",
    "dup.hotkeys": "Клавиши: S — пропуск первой группы в списке, A — подставить «оставить», D — предпросмотр, J — окно просмотра.",
    "dup.delete.count": "К удалению: {n} файл(ов)",
    "dup.delete.approve_only": "Только группы с «Утвердить».",
    "dup.delete.only_reviewed": "Учитывать только группы, отмеченные «Просмотрено»",
    "dup.delete.apply_suggested": "Отметить к удалению",
    "dup.delete.preview": "Предпросмотр удаления",
    "dup.delete.trash": "В корзину",
    "dup.delete.permanent": "Удалить безвозвратно",
    "dup.groups.summary.empty": "Нет групп — выполните сканирование.",
    "dup.groups.summary": "Всего групп: {total}. После фильтров: {filt}. Удаление — только для групп с «Утвердить».",
    "dup.show_more": "Показать ещё",
    "dup.show_all": "Показать все",
    "dup.card.skip": "Пропустить группу",
    "dup.card.approve": "Утвердить",
    "dup.card.delete_entire": "Удалить всю группу",
    "dup.card.reviewed": "Просмотрено",
    "dup.card.compare": "Сравнить в ряд (без ИИ)",
    "dup.card.keep": "Оставить",
    "dup.thumb.loading": "Загрузка…",
    "dup.thumb.video_no_frame": "Видео\n(нет кадра)",
    "dup.thumb.no_preview": "Нет превью",
    "dup.thumb.ffmpeg_try": "Пробуем извлечь кадр видео…",
    "dup.thumb.decode_failed": "Не удалось извлечь кадр",
    "dup.log.video_preview_ffmpeg": "Дубликаты: для превью видео нужны ffmpeg/ffprobe (PATH или PHOTO_AI_SORTER_FFMPEG). Подробности: {msg}",
    "dup.progress.files": "{done} / {total}",
    "dup.progress.stage_detail": "{stage} — {done}/{total}",
    "dup.finished.with_reason": "{done} ({reason})",
    "dup.card.group_title": "Группа {n} — {count} файлов",
    "dup.card.exact_suffix": " (байтовые)",
    "dup.compare.title": "Сравнение группы",
    "dup.compare.hint": "Крупные превью. ИИ здесь не вызывается — LLM включается только при сканировании (чекбокс выше).",
    "dup.compare.ask_model": "Спросить модель (первые два файла)",
    "dup.compare.ask_busy": "Запрос к модели…",
    "dup.compare.ask_dup": "Модель: вероятный дубликат (одна сцена).",
    "dup.compare.ask_not_dup": "Модель: скорее разные кадры.",
    "dup.compare.ask_error": "Ошибка запроса: {err}",
    "dup.compare.no_frame": "Нет кадра для запроса к модели (проверьте ffmpeg для видео).",
    "dup.delete.progress_title": "Удаление файлов",
    "dup.delete.progress_label": "Удаление…",
    "dup.delete.progress_count": "{done} / {total}",
    "dup.delete.progress_file": "{name}",
    "dup.delete.progress_cancel": "Отмена",
    "dup.delete.cancelled_partial": "Удалено {k} из {total} файлов. Операция прервана.",
    "dup.delete.cancelled_none": "Удаление отменено.",
    "dup.delete.confirm.title": "Подтверждение удаления",
    "dup.delete.only_reviewed_note": "\n(Режим: только группы с отметкой «Просмотрено».)",
    "dup.journal.empty": "Журнал удалений пуст.",
    "dup.journal.title": "Журнал удалений",
    "dup.profile.saved": "Профиль сохранён: {name}",
    "dup.profile.none": "Нет сохранённых профилей.",
    "dup.profile.loaded": "Профиль загружен: {name}",
    "dup.compare.one_file": "В группе один файл — нечего сравнивать.",
    "dup.ffmpeg.ok": "Превью видео: ffmpeg найден ({path}).",
    "dup.ffmpeg.missing": "Превью видео: ffmpeg не найден — кадры могут не грузиться; задайте PATH или PHOTO_AI_SORTER_FFMPEG.",
    "dup.stage.start": "Этап: запуск…",
    "dup.stage.scan": "Этап: анализ файлов — читаем файлы и считаем отпечатки; при большой папке это может занять много времени. Можно поставить на паузу.",
    "dup.stage.grouping": "Этап: группировка — объединяем кандидатов в группы.",
    "dup.stage.llm": "Этап: проверка LLM — запросы к модели по спорным парам; длительность зависит от API.",
    "dup.stage.done": "Этап: завершено",
    "dup.stage.generic": "Этап: {name}",
    "dup.finished.summary": "Скан завершён: групп {groups}, файлов в группах {files}, к удалению сейчас (по выбору «оставить»): {to_delete}.",
    "dup.perm.title": "Безвозвратное удаление",
    "dup.perm.checkbox": "Я понимаю, что файлы не попадут в корзину и не все системы позволяют откат.",
    "dup.perm.confirm": "Подтвердить удаление",
    "dup.perm.cancel": "Отмена",
    "dup.groups.none": "Нет групп — выполните сканирование.",
    "dup.review.open": "Просмотр результатов (файл на диске)",
    "dup.review.pick_file": "Выберите result.json из папки duplicate_runs",
    "dup.review.title": "Результаты поиска дубликатов",
    "dup.review.subtitle": "Групп: {groups}, записей в кеше: {records}",
    "dup.review.group_line": "Группа {n} — {nfiles} файлов{tag}",
    "dup.review.suggested": "Подсказка «оставить»: {path}",
    "dup.review.truncated": "… ещё {n} путей",
    "dup.review.records_only": "В файле только записи кеша ({n}), без списка групп.",
    "dup.review.close": "Закрыть",
    "dup.card.keep_multi_hint": "Отметьте файлы, которые оставить; снятые можно удалить.",
    "dup.card.many_files_banner": "Большая группа: {total} файлов. Миниатюр на карточке: {shown}.",
    "dup.card.show_more_thumbs": "Ещё миниатюры (+{n})",
    "dup.card.tail_hint": "Остальные файлы без миниатюры на карточке — откройте список или загрузите ещё превью.",
    "dup.card.open_full_list": "Список: отметить «оставить»…",
    "dup.card.modal.title": "Группа {n}: флаги «оставить»",
    "dup.card.modal.page_info": "Стр. {page} из {pages} ({a}–{b} из {total})",
    "dup.card.modal.prev": "Назад",
    "dup.card.modal.next": "Вперёд",
    "dup.card.modal.close": "Закрыть",
}


def t(key: str, **kwargs: Any) -> str:
    txt = TEXTS.get(key, key)
    if kwargs:
        return txt.format(**kwargs)
    return txt
